name: Code Quality Checks

on:
  push:
    branches:
      - feat/*
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v4
      - name: Call action to install dependencies
        uses: ./.github/actions/deps_install
      - name: Check if any files were changed
        id: file-check
        run: |
          CHANGED=$(git diff --name-only ${{ github.event.before }} ${{ github.sha }} | wc -l)
          echo "changed=$CHANGED" >> $GITHUB_OUTPUT

      - name: Lint code conditionally
        if: steps.file-check.outputs.changed != '0'
        run: npm run lint

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v4
      - name: Call action to install dependencies
        uses: ./.github/actions/deps_install
      - name: Test code
        id: run-tests
        run: npm run test
      - name: Upload test report
        if: failure() && steps.run-tests.outcome == 'failure'
        uses: actions/upload-artifact@v4
        with:
          name: test-report
          path: test.json
  sonarCloud:
    needs: test
    runs-on: ubuntu-latest
    environment: learning
    steps:
      - name: Get code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Call action to install dependencies
        uses: ./.github/actions/deps_install
      - name: Run SonarCloud Scan
        uses: SonarSource/sonarqube-scan-action@v6
        with:
          args: >
            -Dsonar.projectKey=${{ secrets.SONAR_PROJECT_KEY }}
            -Dsonar.organization=${{ secrets.SONAR_ORGANIZATION }}
            -Dsonar.host.url=${{ secrets.SONAR_HOST_URL }}
            -Dsonar.login=${{ secrets.SONAR_TOKEN }}
  pr_request:
    needs: sonarCloud
    runs-on: ubuntu-latest
    steps:
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v8
        with:
          base: integration
          branch: ${{ github.ref_name }}
          title: "Auto PR from ${{ github.ref_name }}"
          body: "Automated PR created by GitHub Actions"