name: Push Docker Image to Docker Hub

on:
  push:
    tags:
      - "v*"

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    environment: learning
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set image tag from Git tag
        run: |
          echo "IMAGE_TAG=${{ github.ref_name }}" >> $GITHUB_ENV
      - name: Debug Docker Secrets
        run: |
          echo "Username length: ${#DOCKERHUB_USERNAME}"
          echo "Token length: ${#DOCKERHUB_TOKEN}"
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Docker image
        run: |
          docker build \
            -t ${{ secrets.DOCKERHUB_USERNAME }}/${{ secrets.DOCKER_IMAGE_NAME }}:${IMAGE_TAG} \
            .

      # - name: Vulnerability Scan
      #   uses: aquasecurity/trivy-action@0.33.1
      #   with:
      #     image-ref: ${{ secrets.DOCKERHUB_USERNAME }}/${{ secrets.DOCKER_IMAGE_NAME }}:${IMAGE_TAG}
      #     severity: HIGH,CRITICAL
      #     format: 'table'

      - name: Push Docker image
        run: |
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/${{ secrets.DOCKER_IMAGE_NAME }}:${IMAGE_TAG}
